server:
  host: "127.0.0.1"
  port: 5000

database:
  host: "localhost"
  port: 5432
  dbName: "arch_db"
  username: "postgres"
  password: "postgres"

log:
  level: "debug" # trace | debug | info | warn | error | fatal | panic
