server:
  host: "127.0.0.1"
  port: 5000

database:
  host: "localhost"
  port: "3306"
  dbName: "arch_db"
  username: "shenna"
  password: "Aqilah@21"

log:
  level: "debug" # trace | debug | info | warn | error | fatal | panic
